version: '3.4'

services:
  web.api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: products.webapi
    build:
      context: .
      dockerfile: Web.API/Dockerfile
    ports:
      - "6000:6000"
      - "6001:6001"
  
  products.database:
    image: postgres:latest
    container_name: products.database
    environment:
      - POSTGRES_DB=booking
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1q2w3e$R
    volumes:
      - ./.containers/products-db:/var/lib/postgresql/data
    ports:
      - 5433:5433
      
